import api from './api';

export const adminApi = {
  stats: () => api.get('/admin/dashboard').then((res) => res.data),
  users: (params) => api.get('/admin/users', { params }).then((res) => res.data),
  updateUser: (id, payload) => api.put(`/admin/users/${id}`, payload).then((res) => res.data),
  products: (params) => api.get('/products', { params }).then((res) => res.data),
  createProduct: (payload) => api.post('/products', payload).then((res) => res.data),
  updateProduct: (id, payload) => api.put(`/products/${id}`, payload).then((res) => res.data),
  deleteProduct: (id) => api.delete(`/products/${id}`).then((res) => res.data),
  categories: () => api.get('/categories').then((res) => res.data),
  createCategory: (payload) => api.post('/categories', payload).then((res) => res.data),
  updateCategory: (id, payload) => api.put(`/categories/${id}`, payload).then((res) => res.data),
  deleteCategory: (id) => api.delete(`/categories/${id}`).then((res) => res.data),
  brands: () => api.get('/brands').then((res) => res.data),
  createBrand: (payload) => api.post('/brands', payload).then((res) => res.data),
  updateBrand: (id, payload) => api.put(`/brands/${id}`, payload).then((res) => res.data),
  deleteBrand: (id) => api.delete(`/brands/${id}`).then((res) => res.data),
  orders: (params) => api.get('/admin/orders', { params }).then((res) => res.data),
  updateOrderStatus: (id, payload) => api.put(`/admin/orders/${id}/status`, payload).then((res) => res.data),
  assignDeliveryBoy: (id, payload) => api.put(`/admin/orders/${id}/assign`, payload).then((res) => res.data),
  updateTracking: (id, payload) => api.put(`/admin/orders/${id}/tracking`, payload).then((res) => res.data),
  deliveryBoys: () => api.get('/admin/delivery-boys').then((res) => res.data),
  createDeliveryBoy: (payload) => api.post('/admin/delivery-boys', payload).then((res) => res.data),
  updateDeliveryBoy: (id, payload) => api.put(`/admin/delivery-boys/${id}`, payload).then((res) => res.data),
  deliveryRewards: () => api.get('/admin/delivery-rewards').then((res) => res.data),
  banners: () => api.get('/banners?all=true').then((res) => res.data),
  createBanner: (payload) => api.post('/banners', payload).then((res) => res.data),
  updateBanner: (id, payload) => api.put(`/banners/${id}`, payload).then((res) => res.data),
  deleteBanner: (id) => api.delete(`/banners/${id}`).then((res) => res.data),
  coupons: () => api.get('/coupons').then((res) => res.data),
  createCoupon: (payload) => api.post('/coupons', payload).then((res) => res.data),
  settings: () => api.get('/settings').then((res) => res.data),
  updateSettings: (payload) => api.put('/settings', payload).then((res) => res.data)
};
